# Generated by Django 5.1.5 on 2025-02-16 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_appl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='pizza',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_appl.pizza'),
        ),
    ]
